### ISSUE TITLE
doesn't work with sublime 3.1.1, build 3176

### ISSUE THREAD

**Issue by tobiasgerstenberg** [FichteFoll/FileHistory#44] opened 2018-05-15 19:15 UTC
I get the following error after trying to run `File History: Open recently closed file ...` via the command command palette: 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1034, in run_
    return self.run(**args)
  File "/Users/tobi/Library/Application Support/Sublime Text 3/Installed Packages/File History.sublime-package/file_history.py", line 761, in run
  File "/Users/tobi/Library/Application Support/Sublime Text 3/Installed Packages/File History.sublime-package/file_history.py", line 799, in open_file
  File "/Users/tobi/Library/Application Support/Sublime Text 3/Installed Packages/File History.sublime-package/file_history.py", line 702, in get_history_by_index
IndexError: list index out of range
```

**Comment by FichteFoll** [comment] 2018-05-16 12:06
Does this happen every time, even after restarts?

**Comment by tobiasgerstenberg** [comment] 2018-05-16 14:30
It still doesn't work after a restart. I first got the following message:

```
Unable to open /Users/tobi/Library/Application Support/Sublime Text 3/Packages/File History/FileHistory.sublime-settings
```

After extracting the package via `PackageResourceViewer: Extract Package` this error message doesn't appear anymore but nothing happens after running `File History: Open recently closed file ...`. The focus just goes back to the caret.

**Comment by FichteFoll** [comment] 2019-08-26 17:07
Closing due to a lack of reproduction steps. Some of the recent fixes may have fixed this as well.

**Closed by FichteFoll** 2019-08-26 17:07 UTC
Labels: bug
