### ISSUE TITLE
ESC key closes current buffer

### ISSUE THREAD

**Issue by msantoro12** [FichteFoll/FileHistory#34] opened 2015-04-14 17:35 UTC
When I use the current project popup menu and press the esc key instead of selecting a file it closes my current buffer.

**Comment by FichteFoll** [comment] 2015-04-14 20:05
What kind of view is your "current buffer"? How did you open it?

**Comment by jbjornson** [comment] 2015-04-15 06:13
I'm guessing that you have mistaken the preview mode with the file actually being opened.  The default behavior of the plugin is to only show a preview of the files in the history when you are in the quick panel ("current project popup menu").  If you want to open the file you either have to select the file (press enter) or press the right arrow to use the quick open feature.

Like I said, I'm only guessing here.  If I'm wrong maybe you could try to provide steps to be able to reproduce the error?

**Comment by msantoro12** [comment] 2015-04-15 16:26
I would be glad to show you whats happening. It appears to be happening is in a workspace that has not closed any buffers yet.  I am on a mac and I had the console logging commands for you.

1.  Open sublime, I used command line from a directory but it happens on existing projects too.
2. Open some files.
3. Open the current project history 
![screen shot 2015-04-15 at 12 13 47 pm](https://cloud.githubusercontent.com/assets/2963052/7163761/bbe7af6a-e369-11e4-9ab1-2a699360cca8.png)
4. Press the esc key
![screen shot 2015-04-15 at 12 13 57 pm](https://cloud.githubusercontent.com/assets/2963052/7163790/e60aa9dc-e369-11e4-8fa1-b48e8b91972a.png)

As you can see the buffer I was on closed when I pressed the esc key. This does not happen if buffers in the current workspace have been closed. Of course you could argue that I shouldn't use this feature for projects that have not closed buffers yet, and that is what I will do for now, but I also wonder why it is showing anything in the list when I use the command.

**Comment by FichteFoll** [comment] 2015-04-15 20:32
That sounds weird. I use FileHistory like that all the time but this has never happened to me, and I'd imagine it hasn't for anyone else either (or at least only very few).

I also can not reproduce this with the exact steps you provided. I did notice however that the views are not "previewed" in transient views if the project-only panel is used. I usually use the global history where this works correctly.

Interestingly the project panel also does not generate logging output. I have the feeling that we somehow forgot it in the last few updates and it just didn't get the new changes. @jbjornson, can you check? (I'm rather busy.)

Could you test if it works when using the global history?

**Comment by msantoro12** [comment] 2015-04-15 21:12
It sure does not happen with global. Also it has to be the first time you use FileHistory on the project. The one I used before was working fine this time.

**Comment by FichteFoll** [comment] 2015-04-15 21:31
I was finally able to reproduce the closing view. I think that all files displayed in the panel need to be opened in the project at the time.

**Comment by msantoro12** [comment] 2015-04-16 01:54
Nope. Last directory I tried it on had 500 CSS files.

**Comment by FichteFoll** [comment] 2015-04-16 06:53
Not all files on the project. I mean that you must not have closed any views in the new project (or reopened them) so that all files displayed in the file history panel are opened at the time. 

@jbjornson, could you perhaps take a look at this?

**Comment by FichteFoll** [comment] 2015-04-16 06:53
Otherwise, if you can't reproduce I will try to get to this soonish.

**Comment by msantoro12** [comment] 2015-04-16 15:01
Ahh I see what you mean now. Yes I think you have nailed it down.

**Comment by FichteFoll** [comment] 2016-04-05 16:16
This has been fixed with https://github.com/FichteFoll/FileHistory/pull/37/commits/8785b4ecbb5efdd36727d2f5ca63281aaa07780d (via #37).

**Closed by FichteFoll** 2016-04-05 16:16 UTC
Labels: bug
